export const USER_TYPES = {
  SET_ACCESS_TOKEN: 'USER_TYPES.SET_ACCESS_TOKEN',
  LOGOUT: 'USER_TYPES.LOGOUT',
  LOGIN_REQUEST: 'LOGIN_TYPES.LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_TYPES.LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_TYPES.LOGIN_FAIL',
};
